---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pkekeneshuskey/public_html/
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp *.css $DEPLOYPATH
    - /bin/cp *.ico $DEPLOYPATH
    - /bin/cp -R files/ $DEPLOYPATH
    - /bin/cp -R images/ $DEPLOYPATH 
    - /bin/cp -R papers/ $DEPLOYPATH 
    - /bin/cp -R slideshow/ $DEPLOYPATH 
